[package]
name = "spacecrafts"
version = "0.2.0-beta.0"
authors = ["Bruce Flynn <brucef@ssec.wisc.edu>"]
edition = "2021"
description = "Spacecraft metadata"
keywords = ["spacepacket", "framing", "cadu"]
categories = ["aerospace::space-protocols"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bmflynn/spacecrafts-rs"
default-featuires = ["serde"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0", features = ["derive"] , optional = true}
serde_json = {version = "^1.0", optional = true}
thiserror = "^2.0"

[features]
serde = ["dep:serde", "dep:serde_json"]
